# Generated by Django 2.2.3 on 2019-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RocketLaunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('launch_date_time', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('link', models.ImageField(null=True, upload_to='')),
                ('launch_success', models.BooleanField(blank=True, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=50, null=True)),
                ('wikipedia_link', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
